FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
#COPY package*.json ./
RUN npm install vue

# # Copy the project files
# COPY . .

# # Expose port 8080
# EXPOSE 8080

# # Run the Vue.js application
# CMD ["npm", "run", "serve"]
